# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1

    steps:
      - checkout

      - run:
          name: install
          command: |
            bash install.sh -v -s -b

      - run:
          name: run tests
          command: |
            bash etc/test.sh -e nuckit -v
