channels:
  - bioconda
  - r
  - conda-forge
  - bushmanlab
  - defaults
dependencies:
  - blat
  - r>=3.4.1
  - python<3.7.0
  - r-base
  - r-argparse
  - r-yaml
  - r-stringr
  - r-data.table
  - r-digest
  - bioconductor-s4vectors
  - bioconductor-iranges
  - bioconductor-genomicranges
  - bioconductor-biostrings
  - bioconductor-shortread
  - bioconductor-bsgenome
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - semantic_version
